### ISSUE TITLE
Bug: Decryption fails with atk-show-template

### ISSUE THREAD

**Issue by bwlz** [dellis23/ansible-toolkit#2]
Here's the stacktrace I got:

```python
> atk-show-template db01-dev roles/postgresql/templates/iptables_postgresql.j2                     (git)-[APP-2052] 
Traceback (most recent call last):
  File "/usr/local/bin/atk-show-template", line 13, in <module>
    show_template(args.host, args.path)
  File "/usr/local/lib/python2.7/dist-packages/ansible_toolkit/show_template.py", line 8, in show_template
    inventory = get_inventory()
  File "/usr/local/lib/python2.7/dist-packages/ansible_toolkit/utils.py", line 46, in get_inventory
    return Inventory(inventory_path, vault_password=get_vault_password())
  File "/usr/local/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 145, in __init__
    group.vars = utils.combine_vars(group.vars, self.get_group_variables(group.name, vault_password=self._vault_password))
  File "/usr/local/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 416, in get_group_variables
    self._vars_per_group[groupname] = self._get_group_variables(groupname, vault_password=vault_password)
  File "/usr/local/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 434, in _get_group_variables
    vars = utils.combine_vars(vars, self.get_group_vars(group))
  File "/usr/local/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 605, in get_group_vars
    return self._get_hostgroup_vars(host=None, group=group, new_pb_basedir=new_pb_basedir)
  File "/usr/local/lib/python2.7/dist-packages/ansible/inventory/__init__.py", line 645, in _get_hostgroup_vars
    results = utils.load_vars(base_path, results, vault_password=self._vault_password)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/__init__.py", line 1525, in load_vars
    found, results = _load_vars_from_path(path, results, vault_password=vault_password)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/__init__.py", line 1579, in _load_vars_from_path
    return True, _load_vars_from_folder(path, results, vault_password=vault_password)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/__init__.py", line 1621, in _load_vars_from_folder
    _found, results = _load_vars_from_path(path, results, vault_password=vault_password)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/__init__.py", line 1583, in _load_vars_from_path
    data = parse_yaml_from_file(path, vault_password=vault_password)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/__init__.py", line 774, in parse_yaml_from_file
    data = vault.decrypt(data)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/vault.py", line 138, in decrypt
    raise errors.AnsibleError("Decryption failed")
ansible.errors.AnsibleError: Decryption failed
```
I double-checked my ~/.atk to make sure it's pointed to the correct vault password file, which it is. Be happy to provide any other information needed for troubleshooting.

**Comment by dellis23** [comment]
Thanks @bwlz 

Could you verify that your vault password file doesn't have a trailing newline at the end?  You can do this by running: `vim -b your-vault-file` and then `:set noeol` and finally `:w` to save.  A few of my team members had this issue and this seemed to resolve it.

**Comment by bwlz** [comment]
Nice, that seems to have resolved this particular issue for me!

**Comment by dellis23** [comment]
Awesome!  I'm guessing Ansible does some stripping of this very thing when loading up the vault, so I'm going to dig into the best way to handle it so the functionality here reflects what's being done there.

**Comment by dellis23** [comment]
Thank you for the issue @bwlz .  This should be fixed now.

Please keep em coming!
