### ISSUE TITLE
ansible 2.0 support?

### ISSUE THREAD

**Issue by jkomara** [dellis23/ansible-toolkit#22]
Just came across this today and it looks awesome. I tried running it but it looks like it requires runner and the API was rewritten in 2.0, no longer using runner.

Are there any plans to support 2.0?

Thanks.

**Comment by brianlycett** [comment]
:+1:   :)
Variable precedence has changed a bit in v2 as well, so there might need to be some mods for that.

**Comment by dellis23** [comment]
Unfortunately I'm not using Ansible much anymore, but I'd be happy to take a look at PRs with 2.0 support.

**Comment by jkomara** [comment]
Are you using something else? Just curious what you decided to go with of you did.





On Wed, Jan 27, 2016 at 9:25 AM -0800, "Dan" <notifications@github.com> wrote:












Unfortunately I'm not using Ansible much anymore, but I'd be happy to take a look at PRs with 2.0 support.

**Comment by dellis23** [comment]
@jkomara Sorry for the late response.  I'm using puppet now.  Though I have my beefs with Ansible, the primary reason I've changed is because my employer changed.

**Comment by steenzout** [comment]
@jkomara I've added a tox file which should enable testing against ansible 2.0.

after the PR is merged I can do some work to make it 2.0 compatible.

**Comment by steenzout** [comment]
#28 addresses this issue.

when merged I'll close this.

**Comment by steenzout** [comment]
master branch has code to support Ansible 2.0.

a v2.0.0 will follow in a couple of days.

**Comment by jkomara** [comment]
Awesome! Thank you.

    _____________________________

**Comment by opoplawski** [comment]
There are still two users of ansible.runner - show_vars.py and show_template.py:

```
Traceback (most recent call last):
  File "/bin/atk-show-vars", line 6, in <module>
    from ansible_toolkit.show_vars import show_vars
  File "/usr/lib/python2.7/site-packages/ansible_toolkit/show_vars.py", line 3, in <module>
    from ansible.runner import Runner
ImportError: No module named runner
```

**Comment by steenzout** [comment]
@opoplawski what ansible version are you using?

[our tests](https://travis-ci.org/dellis23/ansible-toolkit/builds/127568518) are passing in ansible 1.9.4 and 2.0.1.0
- 2.0.1.0 in particular => https://travis-ci.org/dellis23/ansible-toolkit/jobs/127568520

**Comment by steenzout** [comment]
oh wait! don't know if the tests cover that code...

**Comment by opoplawski** [comment]
FWIW - ansible 2.0.2.0.

**Comment by steenzout** [comment]
tests don't cover the case above : reference [here](https://coveralls.io/builds/6031920).

need to add tests for this and patch the code...

**Comment by steenzout** [comment]
working on this at [issue-41](https://github.com/dellis23/ansible-toolkit/tree/issue-41) branch.

**Comment by opoplawski** [comment]
Okay, I'll keep an eye on that then.  Still see 4 test failures on that branch at the moment.

**Comment by steenzout** [comment]
yes, I'm still working on this...

**Comment by sylr** [comment]
Hi @steenzout, are you still working on that ?

**Comment by steenzout** [comment]
@sylr this ain't a priority for me anymore.

the current work on this is at this branch: https://github.com/dellis23/ansible-toolkit/tree/issue-41

feel free to PR.

**Comment by aioue** [comment]
Needed the `atk-vault` functionality and don't have the python chops to update this code so instead borrowed heavily from this repo and extracted what I needed. Works with Ansible 2.6.

https://github.com/aioue/pilfer

Needs `pathlib` and `ansible-vault` pip packages and has a hardcoded vault password path right now but works the same way as atk-vault. Doesn't use the ansible libraries, but rather a 3rd party wrapper that is currently being supported.
