### ISSUE TITLE
increase code coverage

### ISSUE THREAD

**Issue by steenzout** [dellis23/ansible-toolkit#41]
patch code to fix #22

```
There are still two users of ansible.runner - show_vars.py and show_template.py:

Traceback (most recent call last):
  File "/bin/atk-show-vars", line 6, in <module>
    from ansible_toolkit.show_vars import show_vars
  File "/usr/lib/python2.7/site-packages/ansible_toolkit/show_vars.py", line 3, in <module>
    from ansible.runner import Runner
ImportError: No module named runner
```

**Comment by steenzout** [comment]
working on this at [issue-41](https://github.com/dellis23/ansible-toolkit/tree/issue-41) branch.
